# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5-node-browsers
         environment:
           PGHOST: 127.0.0.1
           PGUSER: postgres

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
       - image: circleci/postgres:10
         environment:
           POSTGRES_USER: postgres
           POSTGRES_DB: enju_leaf_dummy_test

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          command: sudo apt install -y openjdk-8-jre-headless
      - run: bundle exec rake db:create RAILS_ENV=test
      - run: bundle exec rake db:migrate RAILS_ENV=test
      - run: bundle exec rake app:sunspot:solr:start RAILS_ENV=test
      - run:
          command: |
            mkdir /tmp/test-results
            bundle exec rspec --format progress \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress
      - save_cache:
          paths:
            - vendor/bundle
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
